### ISSUE TITLE
Addition of new fields to different objects

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/caigo#406]
- [x] Addition of `type` field to the transaction trace objects (addressed in #432)
- [x] Addition of the `l1_gas_price` and `starknet_version` fields to the block header (addressed in #435)
- [x] Replacing `block hash` in `starknet_traceBlockTransactions` with block_id (addressed in #428)
- [x] Addition of `state_diff` field to trace methods (addressed in #432)
