### ISSUE TITLE
Implement RPCv6

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#458]
Starknet [RPCv060-rc1](https://github.com/starkware-libs/starknet-specs/tree/v0.6.0-rc1)

(Note: this issue was originally created for v0.6.0-rc0. The main changes for rc1 have to do with the transaction v3 types, RESOURCE_BOUNDS_MAPPING, and EXECUTION_RESOURCES. Should double check this issue updates to rc-1).

(Note: We later decided to support rc5. This upgrade is broken down into two PRs 475, 486)

The main changes involve 1) implementing V3 transactions, and 2) updating the fields in various types/structs.

note: We still need to add e2e tests for v3 transactions (note:we are putting this of for a patch given difficulties of working with integration network atm)

Sub-issues:

- [x] #488 

Update Readme:
- [x] #479
- [x] #492 Update the readme (again) to rc5

Update TestSpecVersion to rc4

Upgrade to RC4:
- [x] #486

Tests - 
- [x] #484  Integration tests for v3 transaction

Transaction - types
- [x] #461 Implement the V3 transactions
- [x] #461 Update the broadcast transaction types
- [x] #461 Update the "DECLARE_TXN" types
- [x] #461 Update each transactions version field
- [x] #461 Implement the tx-hash logic, with tests.

Various non-transaction types:
- [x] #463 Implement FEE_PAYMENT
- [x] #463 COMMON_RECEIPT_PROPERTIES, should use FEE_PAYMNET
- [x] #463 PENDING_COMMON_RECEIPT_PROPERTIES, should use FEE_PAYMNET, and additional properties field
- [x] #465 EXECUTION_RESOURCES, update from NumAsHex to int
- [x] #472 EMITTED_EVENT two fields are no longer required
- [x] #471 L1_HANDLER_TXN_TRACE include  requried stateDiff
- [x] #471 FUNCTION_INVOCATION include required execution_resources
- [x] #471 CALL_TYPE enum needs updated

Changes to the spec that don't require changes to starknet.go (eg spec had error, that is now fixed, and matches starknet.go)
- [x] ORDERED_EVENT, ORDERED_MESSAGE type should be int
- [x] Update error message in BLOCK_NOT_FOUND error 
- [x] PENDING_BLOCK_HEADER certain fields should not be present  (the not-required fields are not defined in the starknet.go struct, implicitly satisfying this condition)

Finally:
- [x] Double check all changes match the rc-5 spec
