### ISSUE TITLE
RPCv07 spec changes

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#515]
API file changes:
- [ ] #517 Implement `starknet_getBlockWithReceipts`, and required types (BLOCK_WITH_RECEIPTS, PENDING_BLOCK_WITH_RECEIPTS)
- [ ] #518 Update BLOCK_HEADER
- [ ] #520 L1_HANDLER_TXN.version from felt to "0x0" enum
- [ ] #519 Update FEE_ESTIMATE
- [ ] #520 Implement EXECUTION_RESOURCES and COMPUTATION_RESOURCES

Trace files changes:
- [ ] #520 TRANSACTION_TRACE, DECLARE_TXN_TRACE, DEPLOY_ACCOUNT_TXN_TRACE
- [x] #520 FUNCTION_INVOCATION uses COMPUTATION_RESOURCES instead of EXECUTION_RESOURCES
