### ISSUE TITLE
RPCv0.7.0-rc2

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#533]
- [x] #534 Pending receipts removed
- [x] #534 blockhash and blockNumber removed from receipts
- [x] #534 getTransactionReceipt returns a concrete new type, TXN_RECEIPT_WITH_BLOCK_INFO
- [x] pendingBlockHeader returns l1_data_gas_price and l1_da_mode
- [x] BlockBodyWithReceipts returns TXN_RECEIPT instead of Pending Receipt (TXN_RECEIPT_IN_BLOCK). Already support this
