### ISSUE TITLE
Release v0.7.1 checklist

### ISSUE THREAD

**Issue by rianhughes** [NethermindEth/caigo#615]
Release publish:
- [x] Confirm README.md are consistent (merge https://github.com/NethermindEth/starknet.go/pull/621)
- [x] Examples are consistent (eg re-run the examples)
- [x] List of RPC methods is up-to-date (note: spec version method may need updated)
- [x] Confirm all code merged to main
- [x] Confirm CI tests pass correctly
- [x] Create release version Tag
- [x] Create Release Notes
- [x] Trigger pkg.go.dev refresh (confirm by checking new version is public)

Release announcements
- [x] [#shared-starknet-go](https://demerzelsolutions.slack.com/archives/C05BYLL8CEN)
- [x] [Telegram group](https://t.me/StarknetGo)
- [x] Ping the marketing team about the new release, and share release notes
